version: '2'
services:

  web:
    image: ansible/awx:13.0.0
    container_name: awx_web
    depends_on:
      - redis
      - postgres
    ports:
      - "8051:8052"
    hostname: awxweb
    network_mode: mynetwork
    user: a
    restart: unless-stopped
    volumes:
     - 
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 

  task:
    image: ansible/awx:13.0.0
    container_name: awx_task
    depends_on:
      - redis
      - web
      - postgres
    command: /usr/bin/launch_awx_task.sh
    hostname: awx
    network_mode: mynetwork
    user: a
    restart: unless-stopped
    volumes:
     -
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
      SUPERVISOR_WEB_CONFIG_PATH: '/etc/supervisord.conf'

  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped
    network_mode: mynetwork
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
     -

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    network_mode: mynetwork
    volumes:
      - 
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: 
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: 

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.18.0.1/16

volumes:
  supervisor-socket:
  rsyslog-socket:
  rsyslog-config:
