version: '2'

secrets:
  digital_ocean_account:
   file: "secrets/credentials.env"

   
services:    
 traefik: 
  container_name: 'traefik' 
  image: traefik:2.2
  restart: always 
  networks:
    - traefik
  security_opt: 
   - no-new-privileges:true 
  secrets: 
   - digital_ocean_account  
  environment: 
   - DO_AUTH_TOKEN_FILE=/run/secrets/digital_ocean_account
  command: 
   - '--log.level=DEBUG' 
   - '--entrypoints.web.address=:80' 
   - '--entrypoints.websecure.address=:443'
   - '--providers.docker=true' 
   - '--api.insecure=false' 
   - '--api.dashboard=true'  
   - '--providers.docker.exposedbydefault=false'
   - '--providers.docker.network=traefik'
   - '--certificatesresolvers.default.acme.email=alex@alexhayward.me' 
   - '--certificatesresolvers.default.acme.dnschallenge=true' 
   - '--certificatesresolvers.default.acme.dnschallenge.provider=digitalocean'  
   - '--certificatesresolvers.default.acme.storage=/acme.json'
  ports: 
   - "80:80" 
   - "443:443" 
  volumes: 
   - '/var/run/docker.sock:/var/run/docker.sock:ro' 
   - '/home/alex/traefik/letsencrypt/acme.json:/acme.json' 

# global redirect to https 
  labels: 
   - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)' 
   - 'traefik.http.routers.http-catchall.entrypoints=web' 
   - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https' 
   - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

  # global wildcard certificates
   - 'traefik.http.routers.wildcard-certs.tls.certresolver=default'
   - 'traefik.http.routers.wildcard-certs.tls.domains[0].main=${new_hostname}'
   - 'traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${new_hostname}'
   - 'traefik.http.routers.wildcard-certs.tls.domains[1].main=${new_hostname}'
   - 'traefik.http.routers.wildcard-certs.tls.domains[1].sans=*.${new_hostname}'

  # dashboard
   - 'traefik.enable=true' 
   - 'traefik.http.routers.traefik.rule=Host(`monitor.${new_hostname}`)'
   - 'traefik.http.routers.traefik.tls=true'
   - 'traefik.http.routers.traefik.entrypoints=websecure'
   - 'traefik.http.routers.traefik.service=api@internal'


 portainer:
  container_name: portainer
  restart: unless-stopped
  volumes:
   - '/var/run/docker.sock:/var/run/docker.sock'
   - '/home/alex/configs/portainer:/data'
  network_mode: traefik
  hostname: portainer
  image: portainer/portainer:latest
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.portainer.rule=Host(`admin.${new_hostname}`)"
   - "traefik.http.routers.portainer.tls=true"
   - "traefik.http.routers.portainer.entrypoints=websecure"
   - "traefik.http.services.portainer.loadbalancer.server.port=9000"

 netdata:
  container_name: netdata
  network_mode: traefik
  hostname: netdata
  cap_add:
   - SYS_PTRACE
  security_opt:
   - apparmor:unconfined
  volumes:
   - /proc:/host/proc:ro
   - /sys:/host/sys:ro
   - /var/run/docker.sock:/var/run/docker.sock:ro
  restart: unless-stopped
  image: netdata/netdata
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.netdata.rule=Host(`netdata.${new_hostname}`)"
    - "traefik.http.routers.netdata.tls=true"
    - "traefik.http.routers.netdata.entrypoints=websecure"
    - "traefik.http.services.netdata.loadbalancer.server.port=19999"


 openspeedtest:
  container_name: speedtest
  environment:
   - MODE=standalone
   - TITLE=SpeedTest
  network_mode: traefik
  hostname: speedtest
  restart: unless-stopped
  image: adolfintel/speedtest:latest
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.speedtest.rule=Host(`speedtest.${new_hostname}`)"
    - "traefik.http.routers.speedtest.tls=true"
    - "traefik.http.routers.speedtest.entrypoints=websecure"
    - "traefik.http.services.speedtest.loadbalancer.server.port=80"

 ipa:
  image: adelton/freeipa-server:centos-7
  restart: unless-stopped
  container_name: freeipa
  network_mode: traefik
  hostname: ipa
  environment:
    - IPA_SERVER_HOSTNAME=${new_hostname}
    - IPA_SERVER_IP=${server_ip}
  tty: true
  stdin_open: true
  cap_add:
    - SYS_ADMIN
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /var/lib/ipa-data:/data
  sysctls:
    - net.ipv6.conf.lo.disable_ipv6=0
    - net.ipv6.conf.all.disable_ipv6=0
  security_opt:
    - "seccomp:unconfined"
  command:
    - -U 
    - --domain=${new_hostname}
    - --realm=IPA.ALEXHAYWARD.ME
    - --http-pin=test1234
    - --dirsrv-pin=test1234
    - --ds-password=test1234
    - --admin-password=test1234
    - --unattended
  ports:
    - "53:53/udp"
    - "53:53"
    - "389:389"
    - "636:636"
    - "88:88"
    - "464:464"
    - "88:88/udp"
    - "464:464/udp"
    - "123:123/udp"
    - "7389:7389"
    - "9443:9443"
    - "9444:9444"
    - "9445:9445"
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.ipa.rule=Host(`${new_hostname}`)"
    - "traefik.http.routers.ipa.tls=true"
    - "traefik.http.routers.ipa.entrypoints=websecure"
    - "traefik.http.services.ipa.loadbalancer.server.port=443"



networks:
  traefik:
    external: true