freeipa:
    image: adelton/freeipa-server:centos-7
    restart: unless-stopped
    container_name: freeipa
    network_mode: traefik
    hostname: ipa
    environment:
      - IPA_SERVER_HOSTNAME=${new_hostname}
      - IPA_SERVER_IP=${server_ip}
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - -U 
      - --domain=${new_hostname}
      - --realm=IPA.ALEXHAYWARD.ME
      - --http-pin=test1234
      - --dirsrv-pin=test1234
      - --ds-password=test1234
      - --admin-password=test1234
      - --unattended
    ports:
      - "53:53/udp"
      - "53:53"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ipa.rule=Host(`${new_hostname}`)"
      - "traefik.http.routers.ipa.tls=true"
      - "traefik.http.routers.ipa.entrypoints=websecure"
      - "traefik.http.services.ipa.loadbalancer.server.port=443"