- name: Make sure we have the required groups
  group:
    name: "{{ item }}"
    state: present
  loop: 
    - docker

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
  with_items:
    - "{{ config_dir }}"
    - "{{ traefik_directory }}"

- name: Copy DNS service account
  copy:
    src: "{{ SecretLocation }}"
    dest: "{{ traefik_directory }}/credentials.json"
    owner: "{{ user }}"
    mode: '0644'
 

    

