- name: Change Hostname to '{{ domain }}'
  hostname:
    name: "{{ domain }}"

- name: Update Hosts File with hostname '{{ domain }}'
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1 {{ domain }} ipa'
    line: '{{ server_ip }} {{ domain }} ipa'
    state: present    

- name: Update Hosts Cloud Template with public ip '{{ server_ip }}'
  lineinfile:
    dest: /etc/cloud/templates/hosts.redhat.tmpl
    regexp: '^127\.0\.0\.1 {{ "{{fqdn}}" }} {{ "{{hostname}}" }}'
    line: '{{ server_ip }} {{ "{{fqdn}}" }} {{ "{{hostname}}" }}'
    state: present