---
- name: start portainer
  docker_compose:
    state: present
    project_src: "{{ portainer_dir }}"

- name: restart portainer
  docker_compose:
    state: present
    project_src: "{{ portainer_dir }}"
    restarted: yes
