- name: Install packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - git
        - python3
        - python3-dev
        - python3-pip

- name: Ensure docker-compose is installed
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
    