- hosts: all
  become: true
  vars_files:
    - vars/vars.env
    - vars/ans-var.yml

  tasks:
    - name: Change Hostname to '{{ new_hostname }}'
      hostname:
        name: "{{ new_hostname }}"

    - name: Update Hosts File with hostname '{{ new_hostname }}'
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1 {{ current_hostname }} {{ current_hostname }}'
        line: '{{ public_ip }} {{ new_hostname }} ipa'
        state: present    

    - name: Update Hosts Cloud Template with public ip '{{ public_ip }}'
      lineinfile:
          dest: /etc/cloud/templates/hosts.redhat.tmpl
          regexp: '^127\.0\.0\.1 {{ "{{fqdn}}" }} {{ "{{hostname}}" }}'
          line: '{{ public_ip }} {{ "{{fqdn}}" }} {{ "{{hostname}}" }}'
          state: present

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Make sure we have a 'docker' group
      group:
        name: docker
        state: present
  

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create '{{ user }}' and apply sudo privileges
      user:
        name: "{{ user }}"
        state: present
        groups: [wheel, docker]
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user '{{ user }}'
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Update Yum
      yum:
          name: '*'
          state: latest
    
    - name: Install & enable epel-release
      yum: 
          name: epel-release
          update_cache: yes
          state: latest

    - name: Install packages
      yum:
          name: "{{packages}}"
          update_cache: yes
          state: latest
      vars:
          packages:
            - rng-tools
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
            - epel-release
            - unzip
            - nano
            - git
            - python3-pip
            - python3

          
    - name: Add Docker repo
      get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
      
    - name: Install Docker
      yum:
            name: docker-ce
            state: latest
      
    - name: Start Docker service
      service:
            name: docker
            state: started
            enabled: yes

    - name: upgrade pip
      pip:
        name: 
          - pip
        extra_args: --upgrade
        executable: pip3

    - name: Install Python Modules With pip
      pip:
        name:
          - docker
          - docker-compose
        umask: "0022"
        executable: pip3
            
    - name: Enable rngd
      systemd:
          name: rngd
          state: started
          enabled: yes
          
    - name: adding existing user '{{ user }}' to group sudo
      user:
          name: '{{ user }}'
          groups: [docker]
          append: yes

    - name: create dir
      file: 
        path: /home/{{ user }}/traefik/letsencrypt
        state: directory 
        owner: '{{ user }}'
        group: '{{ user }}'

    - name: touch acme.json for TLS certs
      file: 
          path: /home/{{ user }}/traefik/letsencrypt/acme.json
          state: touch
          mode: '600'
          owner: '{{ user }}'
          group: '{{ user }}'

    - name: Create traefik docker network
      docker_network:
          name: traefik
          state: present


    # - name: Create and start services
    #   community.general.docker_compose:
    #       project_src: docker/docker-compose.yml
    #       state: present
    

        


        