- name: Install packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - git
        - python3-dev
        - python3
        - python3-pip

- name: Install docker SDK & Docker-compose
  pip:
    name:
      - docker
      - docker-compose
    umask: "0022"
    executable: pip3