- name: install kubectl
  apt:
    name: kubectl
    state: present
    force: yes


- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  join_command: "{{ join_command_raw.stdout_lines[0] }}"